- domain: www.feishu.cn
  expiry: 1689494698
  httpOnly: false
  name: tt_scid
  path: /
  secure: false
  value: aFxAcaYPHK3jaL5re5MnkyJfO.x5Ae-FV2XUk-bT8.bWgVYUvJxqzPFXbnv8JmkJ2230
- domain: .feishu.cn
  expiry: 1689494697
  httpOnly: false
  name: Hm_lvt_e78c0cb1b97ef970304b53d2097845fd
  path: /
  secure: false
  value: '1657958682'
- domain: .feishu.cn
  expiry: 1659254697
  httpOnly: true
  name: t_beda37
  path: /
  secure: true
  value: 0f638c89b29f6203a0795f24c4cf4013aa6e293d2aa7565b4098c590acaf7f81
- domain: .feishu.cn
  expiry: 1659254697
  httpOnly: false
  name: swp_csrf_token
  path: /
  secure: true
  value: 2056116b-60cf-4296-88dc-45cbdad19d38
- domain: .feishu.cn
  expiry: 1721030696
  httpOnly: true
  name: session_list
  path: /
  sameSite: None
  secure: true
  value: XN0YXJ0-b5co5c8e-8834-40af-9f64-595c4afe153e-WVuZA
- domain: .feishu.cn
  expiry: 1689494689
  httpOnly: false
  name: locale
  path: /
  secure: false
  value: zh-CN
- domain: .feishu.cn
  expiry: 1721030698
  httpOnly: false
  name: _ga
  path: /
  secure: false
  value: GA1.2.1696089224.1657958684
- domain: www.feishu.cn
  expiry: 1689494699
  httpOnly: false
  name: mtc_sid
  path: /
  sameSite: None
  secure: true
  value: jvzabme35icj11g1rs3bhpv
- domain: .feishu.cn
  expiry: 1665734681
  httpOnly: false
  name: __tea__ug__uid
  path: /
  secure: false
  value: '2807201657958681600'
- domain: .feishu.cn
  expiry: 1660550680
  httpOnly: true
  name: _uuid_hera_ab_path_1
  path: /
  secure: false
  value: '7120878309243617281'
- domain: www.feishu.cn
  expiry: 1689494699
  httpOnly: false
  name: mtc_id
  path: /
  sameSite: None
  secure: true
  value: '209926'
- domain: .feishu.cn
  expiry: 1657958743
  httpOnly: false
  name: _gat_UA-98246768-7
  path: /
  secure: false
  value: '1'
- domain: .feishu.cn
  expiry: 1658131497
  httpOnly: false
  name: landing_url
  path: /
  secure: false
  value: https://www.feishu.cn/
- domain: .www.feishu.cn
  expiry: 1658563483
  httpOnly: false
  name: __tea_cookie_tokens_1658
  path: /
  secure: false
  value: '%257B%2522web_id%2522%253A%25227120878296342480414%2522%252C%2522ssid%2522%253A%252266120028-c6b4-49bc-82cd-9507748d4f0e%2522%252C%2522user_unique_id%2522%253A%25222807201657958681600%2522%252C%2522timestamp%2522%253A1657958683484%257D'
- domain: .feishu.cn
  expiry: 1721030696
  httpOnly: true
  name: session
  path: /
  sameSite: None
  secure: true
  value: XN0YXJ0-b5co5c8e-8834-40af-9f64-595c4afe153e-WVuZA
- domain: www.feishu.cn
  expiry: 1689494699
  httpOnly: false
  name: mautic_device_id
  path: /
  sameSite: None
  secure: true
  value: jvzabme35icj11g1rs3bhpv
- domain: .feishu.cn
  httpOnly: false
  name: Hm_lpvt_e78c0cb1b97ef970304b53d2097845fd
  path: /
  secure: false
  value: '1657958698'
- domain: www.feishu.cn
  expiry: 1689494681
  httpOnly: false
  name: ttcid
  path: /
  secure: false
  value: 03e8a18ff2d04017a42ff3b84673c2f536
- domain: .www.feishu.cn
  expiry: 1658563497
  httpOnly: false
  name: _tea_utm_cache_1161
  path: /
  secure: false
  value: undefined
- domain: www.feishu.cn
  expiry: 1689494699
  httpOnly: false
  name: mautic_session_id
  path: /
  sameSite: None
  secure: true
  value: jvzabme35icj11g1rs3bhpv
- domain: .feishu.cn
  expiry: 3805442337
  httpOnly: true
  name: trust_browser_id
  path: /
  secure: false
  value: ed15811e-787d-4f3d-ba39-bfead4c7483d
- domain: .feishu.cn
  expiry: 1721030689
  httpOnly: true
  name: QXV0aHpDb250ZXh0
  path: /
  sameSite: None
  secure: true
  value: 38f34e7d42b6406889d13132d5269522
- domain: .feishu.cn
  expiry: 1658045098
  httpOnly: false
  name: _gid
  path: /
  secure: false
  value: GA1.2.1092510337.1657958684
- domain: .feishu.cn
  expiry: 1721030697
  httpOnly: true
  name: passport_web_did
  path: /
  sameSite: None
  secure: true
  value: '7120878348129075201'
- domain: .www.feishu.cn
  expiry: 1665734696
  httpOnly: false
  name: MONITOR_WEB_ID
  path: /
  secure: false
  value: cac44335-5caf-43d3-8df2-fa3f9a0324d1
